#!/usr/bin/env python3
"""Get and set config options for ExampleApp."""

from confinator.cli import ConfigCLI
from example_app.config import USER_CONFIG_PATH, SCHEMA_CONFIG_PATH

cli = ConfigCLI(config_file=USER_CONFIG_PATH, schema_file=SCHEMA_CONFIG_PATH)
cli.run()
