#!/usr/bin/env python3

"""Separate config script for the example app."""

from confinator.cli import ConfigCLI
from example_app.config import USER_CONFIG_PATH, SCHEMA_PATH

cli = ConfigCLI(config_file=USER_CONFIG_PATH, schema_file=SCHEMA_PATH)
cli.run()
